name: KU9 Clean Source


on:
  workflow_dispatch:


permissions:
  contents: read


jobs:

  clean:

    name: Clean KU9 Source

    runs-on: ubuntu-latest


    steps:


      - name: Checkout

        uses: actions/checkout@v4



      - name: Show files

        run: |

          echo "Current directory"

          pwd

          echo ""

          echo "Files:"

          ls -la

          echo ""

          find . -maxdepth 2 -type d



      - name: Install tools

        run: |

          sudo apt update

          sudo apt install -y \
            unzip \
            wget \
            python3



      - name: Download apktool

        run: |

          mkdir -p tools


          wget \
          https://github.com/iBotPeaches/Apktool/releases/download/v3.0.3/apktool_3.0.3.jar \
          -O tools/apktool.jar



      - name: Check APK

        run: |

          echo "APK list:"

          ls -lh input || true



      - name: Decode KU9 APK

        run: |

          java -jar tools/apktool.jar \
          d input/ku9.apk \
          -o ku9_decode \
          --force



      - name: Create clean package

        run: |

          mkdir KU9-clean


          echo "Copy java source"


          find . \
          -name "*.java" \
          -not -path "./ku9_decode/*" \
          -exec cp --parents {} KU9-clean/ \;


          echo "Copy resources"


          cp -r ku9_decode/res KU9-clean/


          if [ -d ku9_decode/assets ]; then

            cp -r ku9_decode/assets KU9-clean/

          fi



      - name: Compress

        run: |

          zip -r KU9-clean.zip KU9-clean



      - name: Upload

        uses: actions/upload-artifact@v4

        with:

          name: KU9-clean

          path: KU9-clean.zip
