    - name: Install Android SDK tools

      run: |

        sudo apt update

        sudo apt install -y wget unzip openjdk-17-jdk



    - name: Download Android build tools

      run: |

        mkdir -p android-tools


        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip \
        -O android-tools.zip


        unzip -q android-tools.zip -d android-tools



        mkdir -p $HOME/android-sdk/cmdline-tools/latest


        mv android-tools/cmdline-tools/* \
        $HOME/android-sdk/cmdline-tools/latest/



        export ANDROID_HOME=$HOME/android-sdk


        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
        "platform-tools" \
        "build-tools;35.0.0"



        echo "$ANDROID_HOME/build-tools/35.0.0" >> $GITHUB_PATH
