name: KU9 Decompile


on:
  workflow_dispatch:


permissions:
  contents: read


jobs:

  decompile:

    runs-on: ubuntu-latest


    steps:


    - name: Checkout

      uses: actions/checkout@v4



    - name: Install Java

      run: |

        sudo apt update

        sudo apt install -y \
          wget \
          unzip \
          openjdk-17-jdk



    - name: Prepare tools

      run: |

        mkdir -p tools



    - name: Download apktool

      run: |

        wget \
        https://github.com/iBotPeaches/Apktool/releases/download/v3.0.3/apktool_3.0.3.jar \
        -O tools/apktool.jar



    - name: Download CFR

      run: |

        wget \
        https://www.benf.org/other/cfr/cfr-0.152.jar \
        -O tools/cfr.jar



    - name: Install Android build tools

      run: |

        sudo apt install -y android-sdk-build-tools



    - name: Check

      run: |

        ls -lh input/

        java -version



    - name: Run decompile

      run: |

        chmod +x scripts/decompile.sh

        ./scripts/decompile.sh



    - name: Package

      run: |

        zip -r KU9-source.zip output



    - name: Upload

      uses: actions/upload-artifact@v4

      with:

        name: KU9-source

        path: KU9-source.zip
